#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "blocky"
name = "Blocky"
description.en = "Fast and lightweight DNS proxy as ad-blocker for local network"
description.fr = "Proxy DNS rapide et léger comme bloqueur de publicités pour le réseau local"

version = "0.24~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
website = "https://0xerr0r.github.io/blocky/latest/"
admindoc = "https://0xerr0r.github.io/blocky/latest/"
code = "https://github.com/0xERR0R/blocky"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    url = "https://github.com/0xERR0R/blocky/releases/download/v0.24/blocky_v0.24_Linux_x86_64.tar.gz"
    sha256 = "7e79d4129a62813bd67308f271a159875b38b4715ed7105572d3106ea2750e10"

    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]